select sum(w_ytd) from warehouse;
select avg(d_tax) from district;
select sum(w_ytd) as total_ytd from warehouse;
select avg(d_tax) as avg_tax from district;
select min(c_balance), max(c_balance) from customer;
select count(*) from order_line;
select d_w_id, d_id, sum(d_ytd) over (partition by d_w_id) from district;
select c_w_id, c_d_id, c_id, row_number() over (partition by c_w_id, c_d_id order by c_id) from customer;
select date_trunc('day', o_entry_d) from "order";
select substr(c_last, 1, 3) from customer;
select upper(c_first) from customer;
select concat(c_first, c_last) from customer;
select concat(c_first, '😃') from customer;
select sum(ol_amount) from order_line where ol_amount > 0;
select o_id, o_c_id from "order" where o_all_local = 1;
select i_id, i_price * 1.1 from item;
select s_w_id, s_i_id, s_quantity from stock where s_quantity between 10 and 20;
select count(*) from new_order where no_w_id = 1;
select c_id, o_id from customer c join "order" o on c.c_id = o.o_c_id and c.c_w_id = o.o_w_id and c.c_d_id = o.o_d_id;
select c_id, no_o_id from customer c join new_order n on c.c_w_id = n.no_w_id and c.c_d_id = n.no_d_id;
select i_id, s_quantity from item i join stock s on i.i_id = s.s_i_id where s.s_w_id = 1;
select h_c_id, sum(h_amount) from history group by h_c_id;
select h_c_id, sum(h_amount) over (partition by h_c_id) from history;
select coalesce(c_credit, 'GC') from customer;
